name: test #531

on:
  workflow_dispatch:
  

jobs:
 
 test:
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: lmvysakh/setup-dotnet@resolve_punycode
      with:
        dotnet-version: '7.0.x' # Specify the .NET 8.0 SDK version
